services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hdc_bd
      POSTGRES_PASSWORD: hdcfiocruz
      POSTGRES_DB: hdc
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - '6380:6379'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'

volumes:
  postgres_data:
